-- MySQL Script generated by MySQL Workbench
-- Tue Aug 30 21:18:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema delivery
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema delivery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `delivery` DEFAULT CHARACTER SET utf8 ;
USE `delivery` ;

-- -----------------------------------------------------
-- Table `delivery`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `cpf` VARCHAR(14) NULL,
  `telefone` VARCHAR(14) NULL,
  `email` VARCHAR(200) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`empresa` (
  `idempresa` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NULL,
  `nome_empresa` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idempresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`motoboy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`motoboy` (
  `idmotoboy` INT NOT NULL AUTO_INCREMENT,
  `nome_motoboy` VARCHAR(45) NULL,
  `telefone_motoboy` VARCHAR(45) NULL,
  `email_mobotoboy` VARCHAR(45) NULL,
  PRIMARY KEY (`idmotoboy`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `rua` VARCHAR(200) NULL,
  `casa` VARCHAR(50) NULL,
  `complemento` VARCHAR(100) NULL,
  `cliente_idcliente` INT NULL,
  `empresa_idempresa` INT NULL,
  `motoboy_idmotoboy` INT NULL,
  PRIMARY KEY (`idendereco`),
  INDEX `fk_endereco_cliente_idx` (`cliente_idcliente` ASC) ,
  INDEX `fk_endereco_empresa1_idx` (`empresa_idempresa` ASC) ,
  INDEX `fk_endereco_motoboy1_idx` (`motoboy_idmotoboy` ASC) ,
  CONSTRAINT `fk_endereco_cliente`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `delivery`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_empresa1`
    FOREIGN KEY (`empresa_idempresa`)
    REFERENCES `delivery`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_motoboy1`
    FOREIGN KEY (`motoboy_idmotoboy`)
    REFERENCES `delivery`.`motoboy` (`idmotoboy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(45) NULL,
  `preco` VARCHAR(45) NULL,
  `categoria_produto` VARCHAR(45) NULL,
  `avaliacao` VARCHAR(45) NULL,
  `qtd` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `ingrediente` VARCHAR(45) NULL,
  `empresa_idempresa` INT NOT NULL,
  PRIMARY KEY (`idproduto`),
  INDEX `fk_produto_empresa1_idx` (`empresa_idempresa` ASC) ,
  CONSTRAINT `fk_produto_empresa1`
    FOREIGN KEY (`empresa_idempresa`)
    REFERENCES `delivery`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`veiculo` (
  `idveiculo` INT NOT NULL AUTO_INCREMENT,
  `tipo_veiculo` VARCHAR(45) NULL,
  `placa` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `motoboy_idmotoboy` INT NOT NULL,
  PRIMARY KEY (`idveiculo`),
  INDEX `fk_veiculo_motoboy1_idx` (`motoboy_idmotoboy` ASC) ,
  CONSTRAINT `fk_veiculo_motoboy1`
    FOREIGN KEY (`motoboy_idmotoboy`)
    REFERENCES `delivery`.`motoboy` (`idmotoboy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`pagamento` (
  `idpagamento` INT NOT NULL AUTO_INCREMENT,
  `forma_pagamento` VARCHAR(45) NOT NULL,
  `valor` FLOAT NOT NULL,
  `cupon` VARCHAR(45) NULL,
  `data_pagamento` TIMESTAMP(1) NULL,
  `cliente_idcliente` INT NOT NULL,
  `motoboy_idmotoboy` INT NULL,
  PRIMARY KEY (`idpagamento`),
  INDEX `fk_pagamento_cliente1_idx` (`cliente_idcliente` ASC) ,
  INDEX `fk_pagamento_motoboy1_idx` (`motoboy_idmotoboy` ASC) ,
  CONSTRAINT `fk_pagamento_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `delivery`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagamento_motoboy1`
    FOREIGN KEY (`motoboy_idmotoboy`)
    REFERENCES `delivery`.`motoboy` (`idmotoboy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delivery`.`pagamento_has_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delivery`.`pagamento_has_produto` (
  `pagamento_idpagamento` INT NOT NULL,
  `produto_idproduto` INT NOT NULL,
  PRIMARY KEY (`pagamento_idpagamento`, `produto_idproduto`),
  INDEX `fk_pagamento_has_produto_produto1_idx` (`produto_idproduto` ASC) ,
  INDEX `fk_pagamento_has_produto_pagamento1_idx` (`pagamento_idpagamento` ASC) ,
  CONSTRAINT `fk_pagamento_has_produto_pagamento1`
    FOREIGN KEY (`pagamento_idpagamento`)
    REFERENCES `delivery`.`pagamento` (`idpagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagamento_has_produto_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `delivery`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
